project: default
source:
  repoURL: 'https://github.com/sarika1206/aws-tool.git'
  path: app/
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
